<a href="https://colab.research.google.com/github/Ravi-ranjan1801/DIP-Lab/blob/main/dip_lab_11_Compression_Huffman_%2B_Arithmetic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Lab - 11**

In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import heapq
import time
from collections import Counter

PART 1 — Entropy, Compression Ratio, Redundancy

In [3]:
img1 = cv2.imread('smooth.avif',0)
img2 = cv2.imread('textured.jpg',0)

def entropy(img):
    hist = np.bincount(img.flatten(), minlength=256)
    p = hist / np.sum(hist)
    p = p[p>0]
    return -np.sum(p*np.log2(p))

for name, img in zip(["Smooth","Texture"], [img1,img2]):
    H = entropy(img)
    CR = 8 / H
    RD = 1 - (1/CR)

    print(name)
    print("Entropy:", H)
    print("Compression Ratio:", CR)
    print("Redundancy:", RD)

Smooth
Entropy: 5.630529390003366
Compression Ratio: 1.4208255469198816
Redundancy: 0.2961838262495793
Texture
Entropy: 7.738518220434229
Compression Ratio: 1.0337896444923145
Redundancy: 0.03268522244572136


PART 2 — Huffman Coding (8×8)

In [4]:
img = np.random.randint(0,8,(8,8))
data = img.flatten()

print(img)

[[7 2 3 2 2 4 0 3]
 [6 0 4 6 3 6 4 0]
 [5 1 4 7 2 4 2 3]
 [0 4 2 4 4 6 5 1]
 [4 7 5 5 4 7 2 1]
 [6 4 4 5 7 3 4 6]
 [2 2 7 5 3 0 5 5]
 [2 5 7 1 0 2 0 4]]


In [5]:
freq = Counter(data)

heap = [[wt, [sym, ""]] for sym, wt in freq.items()]
heapq.heapify(heap)

while len(heap) > 1:
    lo = heapq.heappop(heap)
    hi = heapq.heappop(heap)

    for pair in lo[1:]:
        pair[1] = '0' + pair[1]
    for pair in hi[1:]:
        pair[1] = '1' + pair[1]

    heapq.heappush(heap, [lo[0]+hi[0]] + lo[1:] + hi[1:])

huff = sorted(heapq.heappop(heap)[1:], key=lambda x: x[0])

print("Symbol : Code")
for sym, code in huff:
    print(sym, ":", code)

Symbol : Code
0 : 001
1 : 1100
2 : 111
3 : 1101
4 : 01
5 : 101
6 : 000
7 : 100


In [6]:
huff_dict = dict(huff)

encoded = ''.join([huff_dict[x] for x in data])

print("Encoded Bitstream:")
print(encoded)

Encoded Bitstream:
10011111011111110100111010000010100011010000100110111000110011101111110100101111010100010111000110010110101100111110000001011011001101010001111111001011101001101101111101100110000111100101
